version: "3"

services:
  backend:
    container_name: rbf_backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - mongo

  frontend:
    container_name: rbf_frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    volumes:
      - ./database/mongo-entrypoint:/docker-entrypoint-initdb.d:ro
      - ./mongo_data:/data/db
    container_name: rbf_mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - ./database/.env
    command: mongod

  auth:
    container_name: rbf_auth
    restart: unless-stopped
    build:
      context: auth
      dockerfile: Dockerfile
    volumes:
      - ./auth:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    depends_on:
      - mongo

volumes:
  mongo_data:
