FROM node:16-alpine as builder

WORKDIR /usr 
COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build && npm prune --production

# ---

FROM node:16-alpine

ENV NODE_ENV production

WORKDIR /usr

COPY --from=builder --chown=node:node /usr/package*.json ./
COPY --from=builder --chown=node:node /usr/dist/ ./dist/
RUN npm ci --only=production

EXPOSE 80

CMD ["npm", "run", "start:prod"]
